title: Galaxy
description: ""
thumbnail: https://rzei8mczw5.ufs.sh/f/v9xa1lyXWM8usS5lM5OLYPkQpCjwmsig13AtTbFnOaRNlW5d
url: "https://kiiyuru-galaxy.vercel.app/"
isFeatured: false
icons:
  - three
  - glsl
